### ISSUE TITLE
Tox 3.5.1 broke tox-travis

### ISSUE THREAD

**Issue by LukeSkywalker92** [tox-dev/tox-travis#118] opened 2018-10-08 18:17 UTC
This is the output I get for a job that passed the build 2 days ago. I think this is because of tax 3.5.1.

```
5.45s$ tox --installpkg ./dist/pyTMCL-*.whl
Matching undeclared envs is deprecated. Be sure all the envs that Tox should run are declared in the tox config.
py36 create: /home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36
py36 inst: /home/travis/build/LukeSkywalker92/pyTMCL/.tox/.tmp/1-pyTMCL-1.0.3-py3-none-any.whl
ERROR: invocation failed (exit code 2), logfile: /home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/log/py36-1.log
ERROR: actionid: py36
msg: installpkg
cmdargs: '/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/bin/python -m pip install --exists-action w /home/travis/build/LukeSkywalker92/pyTMCL/.tox/.tmp/1-pyTMCL-1.0.3-py3-none-any.whl'
Processing ./.tox/.tmp/1-pyTMCL-1.0.3-py3-none-any.whl
Collecting pyserial (from 1==pyTMCL)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Installing collected packages: pyserial, 1
Exception:
Traceback (most recent call last):
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/lib/python3.6/site-packages/pip/_internal/wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: 1==pyTMCL .dist-info directory not found
py36 installed: pyserial==3.4,pyTMCL==1.0.3
___________________________________ summary ____________________________________
ERROR:   py36: InvocationError for command /home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/bin/python -m pip install --exists-action w /home/travis/build/LukeSkywalker92/pyTMCL/.tox/.tmp/1-pyTMCL-1.0.3-py3-none-any.whl (see /home/travis/build/LukeSkywalker92/pyTMCL/.tox/py36/log/py36-1.log) (exited with code 2)
The command "tox --installpkg ./dist/pyTMCL-*.whl" exited with 1.
Done. Your build exited with 1.
```

**Comment by gaborbernat** [comment] 2018-10-08 18:29
Can you please link the Travis job?

**Comment by LukeSkywalker92** [comment] 2018-10-08 18:46
Here it is: [https://travis-ci.com/LukeSkywalker92/pyTMCL/jobs/150405370](https://travis-ci.com/LukeSkywalker92/pyTMCL/jobs/150405370)
same for py27, py34, py35

Funny thing is that it works with py26: [https://travis-ci.com/LukeSkywalker92/pyTMCL/jobs/150405366](https://travis-ci.com/LukeSkywalker92/pyTMCL/jobs/150405366)

**Comment by gaborbernat** [comment] 2018-10-08 20:05
Probably duplicate of https://github.com/tox-dev/tox/issues/1042

**Closed by gaborbernat** 2018-10-08 20:05 UTC
